chore: Add documentation
hyperledger-labs/zeto pull request #58
Opened 2024-09-05 17:58 UTC by dwertent

The docs will be available here:
https://hyperledger-labs.github.io/zeto

2024-09-06 18:27 UTC, jimthematrix requested changes
Thanks for getting this started @dwertent. Left two small comments if you can take a look. thanks!

2024-09-06 18:27 UTC, jimthematrix commented on doc-site/docs/assets/project-icon.png
this needs to be replaced with the logo for hyperledger labs, rather than hyperledger

2024-09-06 18:27 UTC, jimthematrix commented on doc-site/docs/assets/project-logo.png
this needs to be replaced with the logo for hyperledger labs, rather than hyperledger

2024-12-22 07:33 UTC, Chengxuan commented
replaced by https://github.com/hyperledger-labs/zeto/pull/111

2024-12-22 07:33 UTC, closed without merging